stages:
  generate_wsi_patches_and_embed:
    cmd: python src/data/generate_wsi_patches_and_embed.py --config config/wsi_data_pipe_config.yml
    deps:
      - src/data/generate_wsi_patches_and_embed.py
      - config/wsi_data_pipe_config.yml
      - data/raw
    # outs:
    #   - data/interim/patches_and_embeds:
    #       persist: true
    

  generate_wsi_text_with_patches_and_prompt_embeds:
    cmd: python src/data/generate_wsi_texts.py --config config/wsi_data_pipe_config.yml
    deps:
      - src/data/generate_wsi_texts.py 
      - config/wsi_data_pipe_config.yml
      - data/interim/patches_and_embeds
    # outs:
    #   - data/interim/wsi_texts/:
    #       persist: true
  
  aggregate_all_wsi_texts:
    cmd: python src/data/aggregate_all_wsi_texts.py --config config/wsi_data_pipe_config.yml
    deps:
      - src/data/aggregate_all_wsi_texts.py
      - config/wsi_data_pipe_config.yml
      - data/processed/wsi_texts
    # outs:
    #   - data/processed/:
    #       persist: true